### PR TITLE
251 prerender

### PR DESCRIPTION
**Pull request by AndreyKozlov1984**

### CODE REVIEW

**Comment by AndreyKozlov1984** [comment]
@jordinl83 please review!

**Comment by jordinl83** [comment]
The landscape preview is missing on the serverless landscape: https://deploy-preview-458--landscapeapp.netlify.com/cncf/format=serverless

Other than that it looks fine, although I'm a bit surprised by the amount of code necessary for prerendering.

**Comment by AndreyKozlov1984** [comment]
Thanks, @jordinl83 , that is fixed now.

**Comment by dankohn** [comment]
Ready to merge?

**Comment by dankohn** [comment]
Does it LGTM?

**Comment by jordinl83** [comment]
Looks ready to me

**Comment by AndreyKozlov1984** [comment]
LGTM

**Comment by chris-short** [comment]
Thank you!

**Pull request merged**
