### PR TITLE
Automatically check accessibility

### PR DESCRIPTION
**Pull request by jordinl83**

### CODE REVIEW

**Comment by jordinl83** [comment]
@dankohn this should be good to go, but it won't pass until all the PRs that change each landscape settings are merged.

**Comment by dankohn** [comment]
Please merge the remaining landscape PRs and then LGTM this.

**Comment by jordinl83** [comment]
@dankohn don't have permission to merge OMP or LF Energy landsccapes

**Comment by dankohn** [comment]
I just invited you to LF Energy. You should already have permission for OMP. 

--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
dankohn.com or book on my calendar: dankohn.com/c

**Comment by jordinl83** [comment]
@dankohn My bad, the other landscape I don't have write access is CDF.

**Comment by jordinl83** [comment]
LGTM

**Pull request merged**
