### PR TITLE
Support googlebot=yes on query string; closes #283

### LINKED ISSUE #283: Add support for "&googlebot=yes"
If `&googlebot=yes` then please set isGooglebot to true.

### PR DESCRIPTION
**Pull request by jordinl83**
Implements #283

### CODE REVIEW

**Comment by dankohn** [comment]
https://deploy-preview-296--landscapeapp.netlify.com/cncf/selected=vitess&googlebot=yes does not work for me.

Please test and add LGTM on PRs when they're ready for me to merge.

**Comment by jordinl83** [comment]
@dankohn that is weird. Why is it `selected=vitess` not part of the query string? Regardless of that, `googlebot=yes` should definitely be in the query string: https://deploy-preview-296--landscapeapp.netlify.com/cncf/selected=vitess?googlebot=yes

**Comment by dankohn** [comment]
I want to be able to find a URL like https://deploy-preview-296--landscapeapp.netlify.com/cncf/selected=vitess and append `&googlebot=yes` and have it render as it would for GoogleBot. Note that there is code that rewrites all non-permitted URLs. I think you need to add googlebot as a permitted option there.

**Comment by jordinl83** [comment]
LGTM

**Comment by dankohn** [comment]
It is now working (it's showing in the Googlebot format) but it's also deleting the `&googlebot=yes` which it should not.

**Comment by jordinl83** [comment]
> It is now working (it's showing in the Googlebot format) but it's also deleting the `&googlebot=yes` which it should not.

@dankohn yes, that's true. That happens automatically for some reason, I'll check why that is

**Comment by jordinl83** [comment]
@dankohn fixed `googlebot=yes` disappearing from URL

**Comment by jordinl83** [comment]
LGTM

**Pull request merged**
