### PR TITLE
optimize project specific images every day, close #170

### LINKED ISSUE #170: Optimize SVGs in images directory
Note that these SVGs probably shouldn't get the margin added around them. Should we add a flag to svg-autocrop to support no margin?

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**
PRs with new functionality should include a test.

### CODE REVIEW

**Comment by dankohn** [comment]
Please don't optimize them every day. Just a one time thing.

**Comment by ZeusTheTrueGod** [comment]
Ok, then I'll remove it from autoupdate

**Comment by ZeusTheTrueGod** [comment]
LGTM

**Comment by dankohn** [comment]
But the PR should include a one-time optimization of the images.

**Comment by ZeusTheTrueGod** [comment]
Those images are in the project repo, I can not include those images here.

**Comment by dankohn** [comment]
Please add a call for this from package.json. Also, please open a PR in the project repos.

**Comment by ZeusTheTrueGod** [comment]
I've already pushed changes in lfdl repo with these updates.  There is a new PR for a cncf repo, https://github.com/cncf/landscape/pull/1139.
A new command `npm run autocrop-images` has been added

**Comment by ZeusTheTrueGod** [comment]
LGTM

**Pull request merged**
