### PR TITLE
135 pie charts

### PR DESCRIPTION
**Pull request by AndreyKozlov1984**
Testing

### CODE REVIEW

**Comment by dankohn** [comment]
For badges, I suggest allocating them like this:

1L. Project graduated .  1R. LF Project
2L. Open Source Software   2R. Apache License
3L. No CII Badge .    3R. Tweet

And put the member status badge to the right of organization as shown on https://github.com/cncf/landscapeapp/issues/376.

Then, any time a card doesn't have a badge, just leave that area blank.

**Comment by dankohn** [comment]
Please look at why https://deploy-preview-417--landscapeapp.netlify.com/cncf/format=card-mode&grouping=no&license=open-source&selected=zabbix&sort=first-commit doesn't have a pie chart although there's data at https://github.com/zabbix/zabbix.

**Comment by dankohn** [comment]
https://deploy-preview-417--landscapeapp.netlify.com/cncf/category=service-mesh&format=card-mode&grouping=category&selected=linkerd should also show as LF Project.

**Comment by dankohn** [comment]
- [ ] On landscape and portrait mode, please move the chart to be just above Twitter.
- [ ] Adjust the breaks so this doesn't happen:
image

**Comment by dankohn** [comment]
Please change the column chart legend to just say:
`Oct Jan Apr Jul Oct`.

Please change the mouseover to say `2019-09-01` instead of `09/01`.

Please make the pie chart about 2/3rds as tall as it is now and shrink the legend text to be the same font size as `Crunchbase` and `Twitter` to its right.

**Comment by dankohn** [comment]
Add some left margin to the pie chart here:

image

**Comment by dankohn** [comment]
At this width, top fields need to be left justified:

image

**Comment by dankohn** [comment]
Regular `yf` is not yet fetching the activity and language data, but needs to when it's not cached.

**Comment by dankohn** [comment]
Is there an option to only label the y axis with integers?

image

https://deploy-preview-417--landscapeapp.netlify.com/omp/selected=ambitus

**Comment by dankohn** [comment]
The CII badge is now cut off:

https://deploy-preview-417--landscapeapp.netlify.com/cncf/format=card-mode&grouping=no&license=open-source&selected=ceph&sort=first-commit

image

Let's change to "**CII Best Practices** 79%" by removing `In Progress` to make it fit.

**Comment by dankohn** [comment]
Work correctly on shorter screens:

image

**Comment by dankohn** [comment]
- [ ] Hide these graphs on `embed=yes`.

**Comment by dankohn** [comment]
- [ ] Justification issues at this width:

image

**Comment by AndreyKozlov1984** [comment]
LGTM

**Pull request merged**
