### PR TITLE
Fix broken layout in embedded twitter timeline; Fix #331

### LINKED ISSUE #331: Embedded tweets look broken on Safari iphone
Simulator Screen Shot - iPhone Xʀ - 2019-09-12 at 06 12 48

### PR DESCRIPTION
**Pull request by jordinl83**
| Before | After |
| --- | --- |
| before | after |

### CODE REVIEW

**Comment by dankohn** [comment]
Viewing the Twitter for Rook on my iPhone, this branch looks good while master does not.

**Comment by jordinl83** [comment]
@dankohn thinking of just applying this hack if we detect the browser is Safari on iPhone/iPad. Something like `currentDevice.ios() && navigator.vendor.indexOf("Apple") === 0`. What do you think?

**Comment by dankohn** [comment]
Sounds good. Please merge once you confirm it's working.

**Comment by jordinl83** [comment]
LGTM

**Pull request merged**
