### PR TITLE
 fix for a text zoom, close #378

### LINKED ISSUE #378: Scale text with browser zoom
This is at 67% zoom.

image
image

### PR DESCRIPTION
**Pull request by AndreyKozlov1984**
Works in Chrome, but have not tried how good it is for FF and other browsers

### CODE REVIEW

**Comment by AndreyKozlov1984** [comment]
LGTM in Chrome and FF

**Comment by dankohn** [comment]
It also looks good in Safari. Good job.

Please remove the commented out code and merge.

**Comment by AndreyKozlov1984** [comment]
Works fine in Edge
LGTM

**Comment by AndreyKozlov1984** [comment]
Ok, I'll remove commented out code

**Pull request merged**
