### PR TITLE
Improvements to CSS responsiveness; Fixes #246

### LINKED ISSUE #246: Use smaller Twitter icon
On the iPhone, in card mode we’re showing the bigger Twitter icon. Please show the smaller one instead. 

A19A72A4-61B3-4BE1-B607-6389F4B2D06D

### PR DESCRIPTION
**Pull request by jordinl83**
Improvements to CSS responsiveness. Especially around positions of tweet button and landscape controls.

Gif resizing screen:
css-responsiveness

Appearance on iphone:

iphone

Appearance on ipad:

ipad

### CODE REVIEW

**Comment by dankohn** [comment]
Looks promising. Twitter embeds are cropped:

image

**Comment by jordinl83** [comment]
@dankohn seeing the same issue with twitter embed on production: https://landscape.cncf.io/selected=ti-kv

I think this is related to long URLs in tweets, they are not being shortened or truncated. I think my _hack_ will fix this, but I haven't implemented it yet. 

Seeing how large this PR is, it might be a good idea to fix the embed on a separate PR. What do you think?

**Comment by dankohn** [comment]
Sure. I'm happy to merge when you say it's ready.

**Comment by jordinl83** [comment]
@dankohn it's good to go then

**Pull request merged**
