### PR TITLE
Allow duplicate repos; Close #314

### LINKED ISSUE #314: Allow duplicate repo_url entries
Use case is for the Open Mainframe Landscape - see https://landscape.openmainframeproject.org/category=zowe-conformant&format=card-mode&grouping=category&organization=ibm

An offering can be in one or more categories. For commercial apps, I can get around the name duplication check by adding an extra identifier on the name. But for open source apps, I can't repeat a repo so have to leave the repo field blank on the other offerings and thus they won't pull GitHub info.

### PR DESCRIPTION
**Pull request by jordinl83**

### CODE REVIEW

**Comment by jordinl83** [comment]
LGTM

Added duplicate entry for Feilong:
Screenshot 2019-09-25 at 15 06 51

It appears twice in landscape
Screenshot 2019-09-25 at 15 07 11

**Comment by dankohn** [comment]
@jmertic Please try this out.

**Comment by jmertic** [comment]
@dankohn How can I test this? Tried the below and it didn't pull in the update:

```rm -rf node_modules && npm install && yf```

**Comment by jmertic** [comment]
@dankohn NM - did ```npm run build``` first and then ```rm -rf node_modules && npm install && yf``` which seemed to fix it. 

Works great! Thank you!

**Pull request merged**
