### PR TITLE
Check project membership; Fix #495

### LINKED ISSUE #495: Fail when project-related projects are not owned by the project
https://github.com/cdfoundation/cdf-landscape/commit/2924f6640e04e484644f32fdbb09480240d5d872

This update should have failed to build because the project status was changed by ownership was not changed to CDF. Please add an additional build check.

### PR DESCRIPTION
**Pull request by jordinl83**

### CODE REVIEW

**Comment by jordinl83** [comment]
@dankohn not sure if this is the best approach, but first I get the IDs of the children of `relation.values` whose ID is `hosted`, for [CNCF](https://github.com/cncf/landscape/blob/master/settings.yml#L32-L58) that means `graduated, incubating and sandbox`. And compare `item.project` against these values, if it matches then I check if `item.project` is `settings.global.self` or a subsidiary.

With this logic I'm getting some failures:

```
4:50:10 PM: FATAL: Project Horovod has been added to incubating category but does not belong to UCF
4:50:10 PM: FATAL: Project Angel-ML has been added to incubating category but does not belong to UCF
4:50:10 PM: FATAL: Project Acumos has been added to graduated category but does not belong to UCF
4:50:10 PM: FATAL: Project Pyro has been added to incubating category but does not belong to UCF
4:50:10 PM: FATAL: Project Elastic Deep Learning (EDL) has been added to incubating category but does not belong to UCF
```

```
4:50:14 PM: FATAL: Project Baetyl has been added to at_large category but does not belong to LFEdge
4:50:14 PM: FATAL: Project Fledge has been added to growth category but does not belong to LFEdge
```

**Comment by jordinl83** [comment]
@dankohn thoughts on this? ☝️

**Comment by jordinl83** [comment]
@dankohn when you have a minute, could you review this ☝️ ?

**Comment by dankohn** [comment]
Can we please merge this? It is correctly finding errors, in that the UCF and Edge landscapes started from LFAI and didn't remove hosting values. I'll merge pull requests to those 2 landscapes (which are not yet ready for public consumption) and then we can merge this, OK?

**Comment by jordinl83** [comment]
@dankohn I'll merge master first to see that everything still works

**Comment by dankohn** [comment]
Can you please fix these entries on those two landscapes (which are still be developed) and merge this?

**Comment by jordinl83** [comment]
@dankohn Getting another error for the CNCF now. What's the fix for these landscapes? To remove the membership on these items for the time being? Can't merge this PR until these errors are addressed.

```
Project Volcano has been added to sandbox category but does not belong to CNCF
```

```
Project Horovod has been added to incubating category but does not belong to UCF
Project Angel-ML has been added to incubating category but does not belong to UCF
Project Acumos has been added to graduated category but does not belong to UCF
Project Pyro has been added to incubating category but does not belong to UCF
Project Elastic Deep Learning (EDL) has been added to incubating category but does not belong to UCF
```

```
Project Baetyl has been added to at_large category but does not belong to LFEdge
Project Fledge has been added to at_large category but does not belong to LFEdge
```

**Comment by dankohn** [comment]
The volcano one found a legitimate error that I'll fix now (which was the point of the PR). For the others, please change the Crunchbase to be UCF or LF Edge so they can see how to organize their hosted projects when they start updating their landscapes.

**Pull request merged**
