### PR TITLE
Re-write `mobile.twitter.com` to `twitter.com`

### PR DESCRIPTION
**Pull request by jmertic**

### CODE REVIEW

**Comment by jmertic** [comment]
@AndreyKozlov1984 - can you take a peek at this one? This fixes an issue where the Crunchbase profile is locked and the Twitter starts with `mobile.twitter.com`; seems safe to rewrite vs reject.

**Review by AndreyKozlov-sy — APPROVED** [review]

**Comment by AndreyKozlov1984** [comment]
Let me just replace "mobile.twitter" with "twitter"!

**Comment by AndreyKozlov1984** [comment]
there is one minor issue, off by 1, let me merge and fix it!

**Comment by jmertic** [comment]
Thank you sir!

**Pull request merged**
