### PR TITLE
making a small tweet icon, #246

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**
PRs with new functionality should include a test.

### CODE REVIEW

**Comment by ZeusTheTrueGod** [comment]
image

**Comment by ZeusTheTrueGod** [comment]
@dankohn this?

**Comment by dankohn** [comment]
Your screenshot is correct but it's not working on https://deploy-preview-247--landscapeapp.netlify.com/cncf/format=card-mode

**Comment by ZeusTheTrueGod** [comment]
@dankohn please check again. Looks great to me on xCode simulator

**Comment by dankohn** [comment]
It looks correct on my Iphone in portrait mode but not when I make Chrome super narrow. Also, can we use the larger one in portrait mode?

**Comment by ZeusTheTrueGod** [comment]
What exactly is a larger one? A larger icon ?

**Comment by dankohn** [comment]
The Twitter icon should look like this in landscape mode:

image

When I make the Chrome window as narrow as possible, it should switch to just a bird.

**Comment by dankohn** [comment]
Fixed instead with https://github.com/cncf/landscapeapp/commit/d97ce6c3d15df8b76479ebbe2a12b213a9d805c7

**Pull request closed without merging**
