### PR TITLE
properly handle enduser=no in url, close #265

### LINKED ISSUE #265: End User Supporters showing when enduser=no
No End User Supporter should show in this view:

https://landscape.cncf.io/category=cncf-members&enduser=no&format=logo-mode&grouping=category

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**

### CODE REVIEW

**Comment by dankohn** [comment]
Can you please avoid adding any CNCF-specific strings to landscapeapp and instead get the value from a new key in settings.yml.

**Comment by ZeusTheTrueGod** [comment]
Sadly, here it would be hard, because this is a CNCF specific flag and it is used across different parts of the system.

**Comment by ZeusTheTrueGod** [comment]
I'll switch to it though

**Comment by dankohn** [comment]
You can do it as a separate issue, if you want.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Pull request merged**
