### PR TITLE
Use crunchbase to determine if stock has been delisted [Fix #7]

### LINKED ISSUE #7: Fetch crunchbase delisted status
When a company has a stock ticker and IPO status is `delisted`, treat the stock ticker as null.

https://www.crunchbase.com/organization/octo-technology#section-overview
https://www.crunchbase.com/organization/rackspace#section-overview

Then, look at whether you can clear out the `stock_ticker: null` entries from landscape.yml/

### PR DESCRIPTION
**Pull request by jordinl83**

### CODE REVIEW

**Comment by jordinl83** [comment]
LGTM.

See how https://deploy-preview-612--landscapeapp.netlify.app/cncf/data.json does not have stock ticker for "octo-technologies" under `crunchbaseData` but https://landscape.cncf.io/data.json does.

Other stocks that I found were delisted when running update locally were:
* RHT (Red Hat)
* RAX (Rackspace)
* MVNR (Mavenir)
* LNKD (Linkedin)
* CNQR (Concur)
* KING

For those stocks that have a public parent company, we will use the parent's stock ticker.

Companies that are delisted and have `stock_ticker: null` in `landscape.yml` will have `stock_ticker` automatically removed from `landscape.yml`

**Comment by dankohn** [comment]
After the nightly update, will there be any companies going forward that need to manually set `stock_ticker` to null?

**Comment by jordinl83** [comment]
@dankohn not if the company has been delisted

**Comment by dankohn** [comment]
Could you please do the analysis for CNCF. All of the past manual `stock_ticker` were because of delisting or int'l ticket symbols, both of which we should now be handling.

I'd like to confirm whether there are any remaining corner cases before merging.

**Comment by jordinl83** [comment]
There are some more `nulls`. Some are due to the international exchanges, I'll fix those manually after the PR is merged. 

There were others that weren't caused by that issue nor they show as delisted:
```
https://www.crunchbase.com/organization/ctrip: CTRP
https://www.crunchbase.com/organization/ca: CA
https://www.crunchbase.com/organization/ultimate-software: ULTI
```

Also Cookpad has the wrong ticker, it has `O7C.F` but it should be `07C.F`, zero instead of an o.

**Comment by dankohn** [comment]
That's great work. The last 3 look like errors on Crunchbase that I will get
them to fix.
--Dan Kohn <dan@linuxfoundation.org>+1-415-233-1000
General Manager, LF Public Health,lfph.io
dankohn.com or book on my calendar:dankohn.com/c  





On Thu, Jun 11, 2020 8:33 PM, Jordi Noguera notifications@github.com  wrote:


There are some more nulls. Some are due to the international exchanges, I'll fix
those manually after the PR is merged.

There were others that weren't caused by that issue nor they show as delisted:

https://www.crunchbase.com/organization/ctrip: CTRP
https://www.crunchbase.com/organization/ca: CA
https://www.crunchbase.com/organization/ultimate-software: ULTI


Also Cookpad has the wrong ticker, it has O7C.F  but it should be 07C.F, zero
instead of an o.

**Pull request merged**
