### PR TITLE
Improve styling of modal for small screens; Close #363

### LINKED ISSUE #363: Improve styling of card modal on small screens
The card modal has 40px margin and 20px padding on each side on mobile, this means that on 360px wide devices, there's 120px wasted and the content is just shown in 240px.

I would suggest making the modal take the full width and height or just have some small margin on the outside. See below for how each different option would look like:

current | full width/height | 5px 
--| -- | -- 
current | 0px | 5px

10px | 15px | 20px
-- | -- | --
10px | 15px | 20px

### PR DESCRIPTION
**Pull request by jordinl83**

### CODE REVIEW

**Comment by AndreyKozlov1984** [comment]
How have you made it as a Draft?

**Comment by jordinl83** [comment]
@AndreyKozlov1984 you can choose if the PR is a regular PR or a draft before creating it

Screenshot 2019-10-11 at 11 14 23

**Comment by jordinl83** [comment]
#### iphone:
iphone

#### mobile android:
android

#### ipad:
ipad

#### responsiveness:
responsiveness

**Comment by jordinl83** [comment]
Also added swipe left/right to move between cards on mobile/tablet.

**Comment by jordinl83** [comment]
LGTM

**Comment by dankohn** [comment]
@jordinl83 I don't like the most narrow version of this. I'd like to still be able to see some of the background on the left and right margins, and to dismiss the modal by clicking there, instead of needing to scroll to the top to click the x.

**Comment by jordinl83** [comment]
@dankohn don't think being able to tap outside to close the modal and efficiently use screen space are compatible...

Below are some screenshots showing how the modal looks with different paddings:

| Current (5px) | 10px | 15px |
| - | - | - |
| 5px | 10px | 15px | 

| 20px | 25px |
| - | - |
| 20px | 25px |

As you can see, the content underneath starts showing at around 20-25px and I think that would be a narrow area to allow tapping to close (it would work but it would be weird).

Bootstrap modals just have 8px padding on small screens. And the example they have on MUI documentation about responsive modals, they make it fullscreen:

| Bootstrap | MUI |
| - | - |
| bootstrap | material-ui |

I think in small screens less padding is better than more... If the issue is having to scroll to close the modal, I could make the close icon positioned absolute so it's always visible.

**Comment by jordinl83** [comment]
Also, what do you think about removing "https://www." from URLs and showing some of the content in columns?

**Comment by dankohn** [comment]
Could you please do a branch with 20 px so I can compare side to side. Yes, please create a separate issue for shortening URLs.

**Comment by jordinl83** [comment]
@dankohn pushed https://deploy-preview-400--landscapeapp.netlify.com/cncf/

**Pull request closed without merging**
