### PR TITLE
#75, weekly update

### PR DESCRIPTION
**Pull request by AndreyKozlov1984**

### CODE REVIEW

**Comment by AndreyKozlov1984** [comment]
LGTM - few major updates with breaking changes.
"Download CSV" still works.
Sitemap produces the same output as before.
local `npm run open:src` works properly.

**Comment by dankohn** [comment]
What about the license on the sitemap?

**Comment by AndreyKozlov1984** [comment]
No differences.

**Comment by AndreyKozlov1984** [comment]
I.e. files are identical

**Pull request merged**
