### PR TITLE
treat "true" as "yes" in urls, close #242

### LINKED ISSUE #242: true should redirect to yes
https://landscape.cncf.io/enduser=true should redirect to https://landscape.cncf.io/enduser=yes

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**

### CODE REVIEW

**Comment by ZeusTheTrueGod** [comment]
LGTM

**Comment by dankohn** [comment]
This doesn't work for me. Neither https://deploy-preview-291--landscapeapp.netlify.com/cncf/enduser=yes nor https://deploy-preview-291--landscapeapp.netlify.com/cncf/enduser=true loads.

**Comment by ZeusTheTrueGod** [comment]
@dankohn it works properly now, it was an issue with landscapeapp multiple dashboards and handling wrong urls from bots

**Comment by ZeusTheTrueGod** [comment]
LGTM

**Pull request merged**
