### PR TITLE
387 fix ascii filenames

### PR DESCRIPTION
**Pull request by AndreyKozlov1984**
I don't want to overengineer this.
This will prevent us from having wrong filenames in hosted_logos. When there are latinic non ascii characters, they will be replaced for cached_logos. If there are cyrillic or chinese symbols in cached_logos, and that happens only if a company name is chinese - we already do not allow such cases.

example error for hosted_logos:
```
Processing the tree
FATAL: please rename LLVMû.svg to LLVMu.svg
```
For omp-landscape, I'll remove  a cached_logo and then I'll commit a new version to the master

### CODE REVIEW

**Comment by dankohn** [comment]
Could you please do the rename automatically rather than complaining to the user?

**Comment by AndreyKozlov1984** [comment]
I can, just node.js fails to do renaming with those symbols, I'll try to do it with a bash command from nodejs.

**Comment by AndreyKozlov1984** [comment]
Ok, done. Now I automatically rename.

**Comment by AndreyKozlov1984** [comment]
LGTM

**Pull request merged**
