### PR TITLE
suppress annoying warnings, close #497

### LINKED ISSUE #497: Turn off devtools messages in autocrop
https://app.netlify.com/sites/landscape/deploys/5e14d83fbac6bb37d92ab5f9

2:19:15 PM: DevTools listening on ws://127.0.0.1:34607/devtools/browser/0880c3f3-ccfc-43a7-b9b5-44aa3ecdbf73
2:19:15 PM: DevTools listening on ws://127.0.0.1:36769/devtools/browser/11486af8-f65f-4c8f-b4a7-8970d358ad86
2:19:15 PM: DevTools listening on ws://127.0.0.1:45959/devtools/browser/23084918-3fbd-42d1-97df-75dadcaf3d8f
2:19:15 PM: DevTools listening on ws://127.0.0.1:38783/devtools/browser/2d7c6b5c-75f7-4d4e-b503-464f781f6bb1
2:19:15 PM: DevTools listening on ws://127.0.0.1:35819/devtools/browser/b894c76b-c0e9-4c7a-b199-593e2b724585

### PR DESCRIPTION
**Pull request by AndreyKozlov1984**

### CODE REVIEW

**Comment by AndreyKozlov1984** [comment]
I removed most of the noise, including an interactive test reporter, still I want to suppress more output in the build phase.

**Comment by dankohn** [comment]
Should I merge?

**Comment by AndreyKozlov1984** [comment]
Please merge that one, I'll continue to work on further suppressing the useless output in other branch

**Comment by AndreyKozlov1984** [comment]
LGTM

**Pull request merged**
