### PR TITLE
fix sharp version, close #477

### LINKED ISSUE #477: Get landscapeapp working on Node 13 with Catalina
After dealing with the problems of https://github.com/cncf/landscapeapp/issues/475#issuecomment-560041646 I got it working with:
```sh
brew install node@12
brew link --overwrite --force node@12
```
Could you please get landscapeapp working with Node 13 on Catalina. There's an issue with compiling sharp where you may want to file an upstream bug.

### PR DESCRIPTION
**Pull request by AndreyKozlov1984**

### CODE REVIEW

**Comment by AndreyKozlov1984** [comment]
@dankohn does this work on your laptop? With a `rm -rf node_modules` and then `npm install` ?

**Comment by AndreyKozlov1984** [comment]
LGTM, after you merge, I'll check if the deployment is ok

**Comment by dankohn** [comment]
Still not good:
```
Dans-MacBook-Pro:landscapeapp (477-fix-sharp)$ node -v && npm -v
v13.3.0
6.13.2
Dans-MacBook-Pro:landscapeapp (477-fix-sharp)$ cd node_modules/
Dans-MacBook-Pro:node_modules (477-fix-sharp)$ rm -rf * .*
rm: "." and ".." may not be removed
Dans-MacBook-Pro:node_modules (477-fix-sharp)$ ..
Dans-MacBook-Pro:landscapeapp (477-fix-sharp)$ npm i

> interactive-landscape@1.0.339 preinstall /Users/dan/Dropbox/Documents/dev/landscapeapp
> npx npm-force-resolutions 2>/dev/null || true


> svg-autocrop@2.0.6 preinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/svg-autocrop
> npx npm-force-resolutions 2>/dev/null || true


> fsevents@1.2.9 install /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v79-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@13.3.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/fsevents
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.3.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1027:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:5)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/13.3.0/bin/node" "/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/fsevents
node-pre-gyp ERR! node -v v13.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/13.3.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)

> puppeteer@1.20.0 install /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/svg-autocrop/node_modules/convert-svg-core/node_modules/puppeteer
> node install.js

Downloading Chromium r686378 - 110.2 Mb [====================] 100% 0.0s 
Chromium downloaded to /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/svg-autocrop/node_modules/convert-svg-core/node_modules/puppeteer/.local-chromium/mac-686378

> puppeteer@2.0.0 install /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/svg-autocrop/node_modules/puppeteer
> node install.js

Downloading Chromium r706915 - 111.8 Mb [====================] 100% 0.0s 
Chromium downloaded to /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/svg-autocrop/node_modules/puppeteer/.local-chromium/mac-706915

> sharp@0.23.4 install /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /Users/dan/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz

> puppeteer@1.20.0 install /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/minimalcss/node_modules/puppeteer
> node install.js

Downloading Chromium r686378 - 110.2 Mb [====================] 100% 0.0s 
Chromium downloaded to /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/minimalcss/node_modules/puppeteer/.local-chromium/mac-686378

> puppeteer@1.20.0 install /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/react-snap/node_modules/puppeteer
> node install.js

Downloading Chromium r686378 - 110.2 Mb [====================] 100% 0.0s 
Chromium downloaded to /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/react-snap/node_modules/puppeteer/.local-chromium/mac-686378

> sharp@0.23.4 install /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

internal/modules/cjs/loader.js:964
    throw err;
    ^

Error: Cannot find module 'minipass'
Require stack:
- /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/lib/pack.js
- /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/lib/create.js
- /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/index.js
- /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/sharp/install/libvips.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/lib/pack.js:27:18)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/lib/pack.js',
    '/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/lib/create.js',
    '/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/index.js',
    '/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/sharp/install/libvips.js'
  ]
}
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/sharp
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

> node-sass@4.13.0 install /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/dan/.npm/node-sass/4.13.0/darwin-x64-79_binding.node

> puppeteer@2.0.0 install /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/puppeteer
> node install.js

Downloading Chromium r706915 - 111.8 Mb [====================] 100% 0.0s 
Chromium downloaded to /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/puppeteer/.local-chromium/mac-706915

> core-js@3.4.2 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/@babel/node/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.10 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/@babel/polyfill/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.2.1 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/eslint-watch/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/bmp/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/core/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/custom/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/gif/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/jpeg/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-blit/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-blur/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-color/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-contain/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-cover/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-crop/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-displace/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-dither/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-flip/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-gaussian/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-invert/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-mask/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-normalize/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-print/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-resize/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-rotate/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugin-scale/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/plugins/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/png/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/tiff/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/types/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/@jimp/utils/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.5.0 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/jimp/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.4.8 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/svg-autocrop/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.9 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/wait-on/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/webpack-bundle-analyzer/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> ejs@3.0.1 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> node-sass@4.13.0 postinstall /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/vendor/darwin-x64-79/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sharp@0.23.4 (node_modules/favicons-webpack-plugin/node_modules/sharp):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 2486 packages from 1099 contributors and audited 1775932 packages in 100.765s

28 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by AndreyKozlov1984** [comment]
@jordinl83 does this work for you on Mac with nodejs 13 ?

**Comment by jordinl83** [comment]
Seeing the same error, although `npm run build` does not fail:

```
> sharp@0.23.4 install /Users/jordi/workspace/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module 'minipass'
Require stack:
- /Users/jordi/workspace/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/lib/pack.js
- /Users/jordi/workspace/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/lib/create.js
- /Users/jordi/workspace/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/index.js
- /Users/jordi/workspace/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/sharp/install/libvips.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/jordi/workspace/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/lib/pack.js:27:18)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jordi/workspace/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/lib/pack.js',
    '/Users/jordi/workspace/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/lib/create.js',
    '/Users/jordi/workspace/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/tar/index.js',
    '/Users/jordi/workspace/landscapeapp/node_modules/favicons-webpack-plugin/node_modules/sharp/install/libvips.js'
  ]
}
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/sharp.node
```

**Comment by jordinl83** [comment]
Closing in favor of https://github.com/cncf/landscapeapp/pull/493

**Pull request closed without merging**
