### PR TITLE
Use right font [Fix #636]

### LINKED ISSUE #636: Very different layout locally and on build server
Removing Roboto means that we're now using a serif font locally that lays out very differently with `yp`. This is a problem because it's impossible to test layouts locally. Can we get them to both use the same font or should we go back to including Roboto?

website
localhost

### PR DESCRIPTION
**Pull request by jordinl83**

### CODE REVIEW

**Comment by jordinl83** [comment]
Turns out it was a font issue. The screenshots are taken on Ubuntu, which does not have Helvetica installed, so the default font is used instead, which is much wider.

I guess if we want to make sure the font renders consistently across OSes we need to bring back Roboto.

LGTM

**Comment by dankohn** [comment]
Please go back to hosting it locally as the font server isn't accessible in China.

**Comment by jordinl83** [comment]
@dankohn serving fonts

**Comment by jordinl83** [comment]
LGTM

**Pull request merged**
