### PR TITLE
allow non required landscapes to fail, close #594

### LINKED ISSUE #594: Don't require success from non-required landscapes
That was the purpose of https://github.com/cncf/landscapeapp/pull/554 but it didn't seem to get implemented.

### PR DESCRIPTION
**Pull request by AndreyKozlov1984**

### CODE REVIEW

**Comment by AndreyKozlov1984** [comment]
LGTM, because it clearly reports
`12:20:58 AM: a landscape lfedge failed but it is required = true`

**Comment by AndreyKozlov1984** [comment]
LGTM

**Comment by AndreyKozlov1984** [comment]
Should we add more landscapes to the landscapes.yml list  without a `required` attribute?

**Comment by dankohn** [comment]
Please remove the `required` tag from all 0 tweet landscapes. Those haven't launched publicly yet and often break the build.

**Comment by AndreyKozlov1984** [comment]
Done, LGTM

**Pull request merged**
